### PR TITLE
regenerate docs site file

### PR DESCRIPTION
**Pull request by mxz96102**

### CODE REVIEW

**Comment by wangkuiyi** [comment]
@mxz96102 Thanks for this PR!

I am far away from being an expert on site-building. What I know about this repo is mostly about those index.html files used to redirect sqlflow.org/XXX to github.com/sql-machine-learning/XXX and to serve the Go import path aliases.

I asked @llxxxll and @tonyyang-svail ; they lack the knowledge about Jeykll too. To make PR reviews effective and efficient, I think we need a video conference to sync up our knowledge.  What do you say?

**Comment by mxz96102** [comment]
@wangkuiyi It's ok with me

**Comment by mxz96102** [comment]
Fix menu link and doc index structure

**Comment by weiguoz** [comment]
After checking the [preview page](https://mxz96102.github.io/sql-machine-learning.github.io/), I believe the PR works. But it is too huge to review the modifications by code.

Would you please list the modifications to help me out? Many thanks!

**Comment by mxz96102** [comment]
Changes today：
- Change index typed window to gif
- Fix index link error
- Rearrange Docs‘ navigation
- Update sqlflow module to latest

**Comment by weiguoz** [comment]
LGTM

**Review by weiguoz — APPROVED** [review]

**Pull request merged**
